### PR TITLE
Tn/add discoverable creds

### PR DESCRIPTION
**Pull request by TylerNoblett**
Adds discoverable login functionality

https://github.com/ashirt-ops/ashirt-server/assets/22867407/f04d4c7c-c172-485b-a9cf-c1c92ffed213

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jkennedyvz** [comment]
If I fudge around and get a longer error message from the backend it explodes the login window size. 

Screenshot 2023-09-27 at 3 17 19 PM




I can't hit enter here to go to the discovery flow. 

image

**Comment by TylerNoblett** [comment]
I'll take a look! @jkennedyvz

**Comment by TylerNoblett** [comment]
@jkennedyvz I fixed the error UI. Also, I'm able to tab over and click on login using the 'enter' key (no mouse) in this video; is this what you're seeing (but without 'enter' starting the flow)?

https://github.com/ashirt-ops/ashirt-server/assets/22867407/03ba9ef5-7602-4dbf-855d-963b746e0347

**Comment by TylerNoblett** [comment]
@jkennedyvz now you can click "Enter" to start the login flow

**Review by jkennedyvz — APPROVED** [review]

**Pull request merged**
