### PR TITLE
Upgrade AWS library to version 2

### PR DESCRIPTION
**Pull request by JoelAtDeluxe**
This PR changes the golang aws library to the v2 golang library, over the v1 library. It may be worthwhile to hold off on merging this PR until after the metadata PRs are merged, as the lambda introduction would also need to be updated.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by JoelAtDeluxe** [comment]
This PR is now out of date. The addition of  lambdas means that we should spend some time trying to make those work. The interface changed slightly, but it might have some broader ramifications. I'm still going through the docs on this one, but my recommendation is to not merge at the moment.

**Comment by jrozner** [comment]
Rebased on main and resolved conflicts. It looks like all the service worker code and lambdas were written against the new library rather than the old one. We can deploy this into staging and test it out before merging and do a pass over it to see if anything else needs to change.

**Review by jkennedyvz — APPROVED** [review]
LGTM

**Review by TylerNoblett — DISMISSED** [review]
code looks good, works for me locally and on aws 🚀

**Review by jkennedyvz — APPROVED** [review]

**Pull request merged**
